### ISSUE TITLE
Extension size 398mb?

### ISSUE THREAD

**Issue by tobilg** [handstuyennn/geo#19]
I did a custom build of the geo extension, and I see a extension size of 398mb:

```bash
$ ls -la --block-size=M /tmp/release"
total 398M
drwxr-xr-x 2 root root   1M Mar 28 12:52 .
drwxrwxrwt 1 root root   1M Mar 28 12:52 ..
-rwxr-xr-x 1 root root 398M Mar 28 12:52 geo.duckdb_extension
```

Is this a problem with my build, or is it really that large?

**Comment by blackrez** [comment]
Use `strip` to shrimp the extension after the compilation.

**Comment by tobilg** [comment]
Thanks @blackrez... Do you have an example command?

**Comment by blackrez** [comment]
Yes it's quite simple.
From my blog 
![image](https://user-images.githubusercontent.com/798369/228255896-7b4ffe07-73fb-4a46-81d9-4b6bc82ecc78.png)

**Comment by tobilg** [comment]
I went with `strip --strip-unneeded geo.duckdb_extension` and the result is this:

```bash
$ ls -la --block-size=M /tmp/release 
drwxr-xr-x 2 root root  1M Mar 28 13:38 .
drwxrwxrwt 1 root root  1M Mar 28 13:38 ..
-rwxr-xr-x 1 root root 19M Mar 28 13:38 geo.duckdb_extension
```

Thanks @blackrez. I'll eventually include this in my [DuckDB Lambda layer](https://github.com/tobilg/duckdb-nodejs-layer).
