### ISSUE TITLE
Copyright information removed

### ISSUE THREAD

**Issue by pramsey** [handstuyennn/geo#2]
Hello! Congratulations on starting a spatial data project! It's a very cool area of work, welcome to the geospatial club :) 

I see you've decided to make some use of PostGIS internals. That's great! We do however, require you to retain our copyright headers (we did write those files, after all) and place your work under the GPLv2 (that's the GPL bargain, share and share alike). Thanks!

**Comment by handstuyennn** [comment]
Hi,

I will add them next commit.
