### ISSUE TITLE
ST_Centroid eats 100% CPU

### ISSUE THREAD

**Issue by blackrez** [handstuyennn/geo#6]
Hello,

The function `ST_Centroid` eats all the CPU

```
SELECT ST_ASTEXT(ST_CENTROID(ST_GEOMFROMWKB(geom))) FROM '/Users/Nabil/Downloads/mutations_d13.parquet'  WHERE valeurfonc=378000000.0;
```

I have to kill the duckdb process.

I tested with shapely and it works without issue. I think it's not the geometry but the function.
```
>>> r = con.execute("SELECT ST_ASGEOJSON(ST_GEOMFROMWKB(geom)) FROM '/Users/Nabil/Downloads/mutations_d13.parquet'  WHERE valeurfonc=378000000.0;")
>>> g = r.fetchall()
>>> s = shape(json.loads(g[0][0])
>>> s.centroid
<POINT (5.469 43.294)>
```

**Comment by handstuyennn** [comment]
Hi @blackrez ,

Could you give me your testing file

Thanks

**Comment by blackrez** [comment]
Yes of course, I will send by email.

**Comment by handstuyennn** [comment]
Hi @blackrez ,

I have tested with your file and everything worked normally. Please build with latest code and test it again.

`SELECT ST_ASTEXT(ST_CENTROID(ST_GEOMFROMWKB(geom))), valeurfonc FROM '/Users/tuyennguyen/Downloads/mutations_d13.parquet' WHERE valeurfonc=378000000.0;`

<img width="1088" alt="report_centroid_functions" src="https://user-images.githubusercontent.com/49063786/215670120-e9b27d03-4f0a-416b-840d-8324c9fc077a.png">

Thanks

**Comment by blackrez** [comment]
Works great (and very fast) with the new version

Thanks a lot @handstuyennn
